### PR TITLE
feat: Add React and React Hook linting rules

### PR DESCRIPTION
**Pull request by RowanTate**
Added new config that extends base rules with react and react hook rules

### CODE REVIEW

**Comment by philals** [comment]
I approve, however keen to have @blacha's eyes on it.

**Comment by blacha** [comment]
:lgtm: the title needs to be conventional or it would be picked up in change log.

random thought does this need to be a seperate config or can we apply it on all `.tsx` files?

**Comment by philals** [comment]
@blacha yeah it could be applied to ALL .tsx files... that use React.. I think one of the fancy new frameworks can also use .tsx... anyway... we'll solve that problem when LINZ starts using Vue.js or what ever the cool kids use these days.

**Thinking about it again.. yeah maybe we should.. The non-tsx developers are installing all the dependencies anyway..**

Thoughts @RowanTate ?

**Comment by RowanTate** [comment]
> :lgtm: the title needs to be conventional or it would be picked up in change log.
> 
> random thought does this need to be a seperate config or can we apply it on all `.tsx` files?

Makes sense. I'll update the PR soon

**Review by blacha — APPROVED** [review]

**Pull request merged**
